Q.1 Create a dataset as follow in the table

In [ ]:
import pandas as pd
data={
    "Tid":[1,2,3,4,5,6,7,8,9,10],
    "Refund":["Yes","No","NO","Yes","No","NO","Yes","No","No","No"],
    "Marital Status":["Single","Married","Single","Married","Divorced","Married","Divorced","Single","Married","Single"],
    "Taxable Income":["125K", "100K", "70K", "120K", "95K", "60KK", "220K", "85K", "75K", "90K"],
    "Cheat":["No","No","No","No","Yes","No","No","Yes","Yes","No"]

}
df=pd.DataFrame(data)
print(df)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     NO         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     NO        Married           60KK    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K   Yes
9   10     No         Single            90K    No

Q.2 From the above table that you have created, locate row 0, 4, 7 and 8 using DataFrame.

In [ ]:
selected_rows=df.iloc[[0,4,7,8]]
print(selected_rows)

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K   Yes

Q.3 Navigate the DataFrame and do the following task for the table created in question 1:
1. Select row from index 3 to 7.
2. Select row from index 4 to 8, and column 2 to 4.
3. Select all rows with column index 1 to 3 (include index 3 during selection).

In [ ]:
rows_3_to_7=df.iloc[3:8]
print("Rows from index 3 to 7:")
print(rows_3_to_7)

Rows from index 3 to 7:
   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     NO        Married           60KK    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

In [ ]:
rows_4_to_8_cols_2_to_4=df.iloc[4:9, 2:5]
print("\nRows from index 4 to 8 and columns 2 to 4:")
print(rows_4_to_8_cols_2_to_4)

Rows from index 4 to 8 and columns 2 to 4:
  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married           60KK    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K   Yes

In [ ]:
all_rows_cols_1_to_3=df.iloc[:, 1:4]
print("\nAll rows with colummns from index 1 to 3:")
print(all_rows_cols_1_to_3)

All rows with colummns from index 1 to 3:
  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     NO         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     NO        Married           60KK
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

Q.4 Read a csv file and display its first five rows.
Note-: Download dataset from https://www.kaggle.com/datasets/uciml/iris)

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving iris.csv.zip to iris.csv.zip

In [ ]:
import pandas as pd
import zipfile

with zipfile.ZipFile('iris.csv.zip', 'r') as zip_ref:
    with zip_ref.open('Iris.csv', 'r') as csv_file:
        df = pd.read_csv(csv_file)

df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Q.5 From the csv file (uploaded in the Q.4) delete row 4, and delete column 3. Display the
result.

In [ ]:
df = df.drop(df.index[4])

if len(df.columns) > 3:
    df = df.drop(df.columns[3], axis=1)
else:
    print("DataFrame has fewer than 4 columns. Skipping column drop.")

print("\nDataFrame after deleting row 4 and column 3:")
print(df.head())

DataFrame after deleting row 4 and column 3:
   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0   1            5.1           3.5           0.2  Iris-setosa
1   2            4.9           3.0           0.2  Iris-setosa
2   3            4.7           3.2           0.2  Iris-setosa
3   4            4.6           3.1           0.2  Iris-setosa
5   6            5.4           3.9           0.4  Iris-setosa

Q.6 Create a sample dataset (employees.csv) containing information about employees in
a company.

In [ ]:
import pandas as pd


data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-18", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

df = pd.DataFrame(data)

df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])

# a)
print("Shape of DataFrame:", df.shape)

# b)
print("\nSummary:\n", df.info())

# c)
print("\nDescriptive Statistics:\n", df.describe())

# d)
print("\nFirst 5 rows:\n", df.head())
print("\nLast 3 rows:\n", df.tail(3))

# e)
print("\nAverage Salary:", df["Salary"].mean())
print("Total Bonus Paid:", df["Bonus"].sum())
print("Youngest Employee Age:", df["Age"].min())
print("Highest Performance Rating:", df["Rating"].max())

# f)
df_sorted = df.sort_values(by="Salary", ascending=False)
print("\nData Sorted by Salary:\n", df_sorted)

# g)
def categorize_rating(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

df["Performance_Category"] = df["Rating"].apply(categorize_rating)

# h)
print("\nMissing Values:\n", df.isnull().sum())

# i)
df.rename(columns={"Employee_ID": "ID"}, inplace=True)

# j)
df_experience = df[df["Years_of_Experience"] > 5]
df_IT = df[df["Department"] == "IT"]

print("\nEmployees with more than 5 years of experience:\n", df_experience)
print("\nEmployees in IT department:\n", df_IT)

df["Tax"] = df["Salary"] * 0.10

# l)
df.to_csv("modified_employees.csv", index=False)
print("\nModified dataset saved as 'modified_employees.csv'")

Shape of DataFrame: (5, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      datetime64[ns]
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(5), object(3)
memory usage: 532.0+ bytes

Summary:
 None

Descriptive Statistics:
        Employee_ID        Age       Salary  Years_of_Experience  \
count     5.000000   5.000000      5.00000             5.000000
mean    103.000000  34.000000  60000.00000             7.400000
min     101.000000  28.000000  50000.00000             3.000000
25%     102.000000  29.000000  55000.00000             4.000000
50%     103.000000  34.000000  60000.00000             8.000000
75%     104.000000  38.000000  65000.00000            10.000000
max     105.000000  41.000000  70000.00000            12.000000
std       1.581139   5.612486   7905.69415             3.847077

              Joining_Date   Bonus    Rating
count                    5     5.0  5.000000
mean   2016-08-19 19:12:00  5500.0  4.100000
min    2010-11-25 00:00:00  4500.0  3.500000
25%    2013-06-01 00:00:00  5000.0  3.800000
50%    2017-07-18 00:00:00  5000.0  4.000000
75%    2020-03-15 00:00:00  6000.0  4.500000
max    2021-02-10 00:00:00  7000.0  4.700000
std                    NaN  1000.0  0.494975

First 5 rows:
    Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-18    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

Last 3 rows:
    Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

Average Salary: 60000.0
Total Bonus Paid: 27500
Youngest Employee Age: 28
Highest Performance Rating: 4.7

Data Sorted by Salary:
    Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-18    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

Missing Values:
 Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

Employees with more than 5 years of experience:
     ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-18
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average
4   Male   5000     3.5              Average

Employees in IT department:
     ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-18
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average

Modified dataset saved as 'modified_employees.csv'